import Head from 'next/head'
import { useQuery, gql } from '@apollo/client'
import LoginButton from '@/components/login-btn'

const TEST_QUERY = gql`
  query GetUserById {
    user(id: "1") {
      id
      name
      email
    }
  }
`

export default function Home() {
  const { loading, error, data } = useQuery(TEST_QUERY)
  if (loading) return <p>Loading...</p>
  if (error) return <p>Error: {error.message}</p>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginButton />
      <h1>ID: {data.user.id}</h1>
      <p>name: {data.user.name}</p>
      <p>email: {data.user.email}</p>
    </>
  )
}
